In [ ]:
import torch

# Torch Tensors

In [ ]:
#This is a 1-D Tensor
a = torch.tensor([2,2,1])
print(a)

tensor([2, 2, 1])


In [ ]:
#This is a 2-D Tensor
b = torch.tensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])
print(b)

tensor([[2, 1, 4],
        [3, 5, 4],
        [1, 2, 0],
        [4, 3, 2]])


In [ ]:
#The size of the tensors
print(a.shape) # attribute
print(b.shape)
print(a.size()) # method
print(b.size())

torch.Size([3])
torch.Size([4, 3])
torch.Size([3])
torch.Size([4, 3])


In [ ]:
#Get the height/number of rows of b
print(b.shape[0])

4


In [ ]:
c = torch.FloatTensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])
#or we can do
# c = torch.tensor([2,2,1], dtype = torch.float)
# c = torch.tensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]], dtype = torch.float)


In [ ]:
d = torch.DoubleTensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])
#or we can do
#d = torch.tensor([2,2,1], dtype = torch.double)

In [ ]:
print(c)
print(c.dtype)

tensor([[2., 1., 4.],
        [3., 5., 4.],
        [1., 2., 0.],
        [4., 3., 2.]])
torch.float32


In [ ]:
print(d)
print(d.dtype)

tensor([[2., 1., 4.],
        [3., 5., 4.],
        [1., 2., 0.],
        [4., 3., 2.]], dtype=torch.float64)
torch.float64


In [ ]:
print(c.mean())

tensor(2.5833)


In [ ]:
print(d.mean())

tensor(2.5833, dtype=torch.float64)


In [ ]:
print(c.std())

tensor(1.5050)


In [ ]:
print(d.std())

tensor(1.5050, dtype=torch.float64)


In [ ]:
#Reshape b
#Note: If one of the dimensions is -1, its size can be inferred
print(b.view(-1,1)) # the method to reshapre a tensor is called view
print(b.view(12))
print(b.view(-1,4)) # row, column
print(b.view(3,4))
#Assign b a new shape
b = b.view(1,-1)
print(b)
print(b.shape)
#We can even reshape 3D tensors
print('\n')
#Create a 3D Tensor with 2 channels, 3 rows and 4 columns (channles,rows,columns)
three_dim = torch.randn(2, 3, 4)
print('\n')
print(three_dim)
print(three_dim.view(2, 12))  # Reshape to 2 rows, 12 columns
print(three_dim.view(2, -1))

tensor([[2],
        [1],
        [4],
        [3],
        [5],
        [4],
        [1],
        [2],
        [0],
        [4],
        [3],
        [2]])
tensor([2, 1, 4, 3, 5, 4, 1, 2, 0, 4, 3, 2])
tensor([[2, 1, 4, 3],
        [5, 4, 1, 2],
        [0, 4, 3, 2]])
tensor([[2, 1, 4, 3],
        [5, 4, 1, 2],
        [0, 4, 3, 2]])
tensor([[2, 1, 4, 3, 5, 4, 1, 2, 0, 4, 3, 2]])
torch.Size([1, 12])




tensor([[[ 0.5572, -0.0966, -0.8857, -0.0790],
         [-1.0658, -1.3216,  1.6341, -0.6019],
         [ 0.4852,  0.1547, -0.5259,  0.0062]],

        [[ 1.2748,  0.8993,  1.4589, -0.0152],
         [ 0.1439,  1.5730, -0.2731,  1.1150],
         [ 0.0346,  0.3214,  0.2166, -1.2798]]])
tensor([[ 0.5572, -0.0966, -0.8857, -0.0790, -1.0658, -1.3216,  1.6341, -0.6019,
          0.4852,  0.1547, -0.5259,  0.0062],
        [ 1.2748,  0.8993,  1.4589, -0.0152,  0.1439,  1.5730, -0.2731,  1.1150,
          0.0346,  0.3214,  0.2166, -1.2798]])
tensor([[ 0.5572, -0.0966, -0.8857, -0.0790, -1.0658

In [ ]:
#Create a matrix with random numbers between 0 and 1
r = torch.rand(4,4)
print(r)

tensor([[0.1655, 0.5509, 0.7215, 0.4266],
        [0.5039, 0.6241, 0.6375, 0.0086],
        [0.8058, 0.3813, 0.5304, 0.6250],
        [0.7783, 0.9672, 0.5758, 0.9691]])


In [ ]:
#Create a matrix with random numbers taken from a normal distribution with mean 0 and variance 1
r2 = torch.randn(4,4)
print(r2)
print(r2.dtype)

tensor([[ 1.2221,  0.5479, -0.1081,  2.5792],
        [-0.1063,  0.1902,  0.4066, -0.7872],
        [-0.4863, -0.5022, -0.0705,  0.5866],
        [ 0.7790, -0.4010, -1.4613,  1.7189]])
torch.float32


In [ ]:
#Create an array of 5 random integers from values between 6 and 9 (exlusive of 10)
in_array = torch.randint(6,10, (5,))
print(in_array)
print(in_array.dtype)

tensor([8, 9, 9, 6, 7])
torch.int64


In [ ]:
#Create a 2-D array (or matrix) of size 3x3 filled with random integers from values between 6 and 9 (exlusive of 10)
in_array2 = torch.randint(6,10, (3,3))
print(in_array2)

tensor([[9, 7, 7],
        [9, 7, 6],
        [7, 7, 8]])


In [ ]:
#Get the number of elemetns in in_array
print(torch.numel(in_array))
#Get the number of elemetns in in_array
print(torch.numel(in_array2))

5
9


In [ ]:
#Construct a 3x3 matrix of zeros and of dtype long:
z = torch.zeros(3, 3, dtype=torch.long)
print(z)
#Construct a 3x3 matrix of ones
o = torch.ones(3,3) # if you don't give dtype, it will use default one - float
print(o)
print(o.dtype)


tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.float32


In [ ]:
r2_like = torch.randn_like(r2, dtype=torch.double)    # Convert the data type of the tensor
print(r2_like) # randn_like - Randn_like，所以这基本上意味着与我们之前学习过的 .Randn 函数相同。然而，当我们放入 _like 时，它​​就占据了 R2 的大小。你正在生成随机整数大小与R2相同，类型为torch.double。

tensor([[ 1.6390,  0.1016,  0.3886,  1.7789],
        [ 0.5381,  0.7601, -0.6157,  1.8600],
        [ 1.5001,  0.7930,  0.2296,  0.3817],
        [-1.1445,  0.2986,  0.5821, -0.8531]], dtype=torch.float64)


In [ ]:
#Add two tensors, make sure they are the same size and data type
add_result = torch.add(r,r2)
print(add_result)

tensor([[ 1.3876,  1.0988,  0.6134,  3.0058],
        [ 0.3976,  0.8143,  1.0441, -0.7786],
        [ 0.3195, -0.1209,  0.4599,  1.2116],
        [ 1.5573,  0.5661, -0.8855,  2.6880]])


In [ ]:
#In-place addition (change the value of r2)
r2.add_(r)    # if you don't want to reassign a new variables, you can directly use like this
print(r2)

tensor([[ 1.3876,  1.0988,  0.6134,  3.0058],
        [ 0.3976,  0.8143,  1.0441, -0.7786],
        [ 0.3195, -0.1209,  0.4599,  1.2116],
        [ 1.5573,  0.5661, -0.8855,  2.6880]])


In [ ]:
print(r2[:,1]) #all rows, column 1 (start from 0 )
print(r2[:,:2]) # all rows, first two column
print(r2[:3,:])# first three rows, all column
num_ten = r2[2,3]  #这只是一个具有一个数字的张量。
print(num_ten)
print(num_ten.item()) # 只需访问张量内部的这个数字
print(r2[2,:])

tensor([ 1.0988,  0.8143, -0.1209,  0.5661])
tensor([[ 1.3876,  1.0988],
        [ 0.3976,  0.8143],
        [ 0.3195, -0.1209],
        [ 1.5573,  0.5661]])
tensor([[ 1.3876,  1.0988,  0.6134,  3.0058],
        [ 0.3976,  0.8143,  1.0441, -0.7786],
        [ 0.3195, -0.1209,  0.4599,  1.2116]])
tensor(1.2116)
1.2115864753723145
tensor([ 0.3195, -0.1209,  0.4599,  1.2116])


## Numpy Bridge

In [ ]:
import numpy as np

In [ ]:
#Converting a Torch Tensor to a NumPy Array
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)
#See how the numpy array changed their value.
a.add_(1)
print(a)
print(b) # 因此 NumPy 数组实际上受到 Torch 张量的影响，这被称为 NumPy Bridge，这就是如何将 Torch Tensor 转换为对 NumPy 数组也影响 NumPy 数组，所以无论 Torch 张量发生什么,在 NumPy 数组上也会发生这种情况。

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [ ]:
#Converting NumPy Array to Torch Tensor
#See how changing the np array changed the Torch Tensor automatically
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b) # 反过来也一样, 互相影响

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [ ]:
#Move the tensor to the GPU
r2 = r2.cuda() #将张量移动到 GPU 的方式
print(r2)
# 当你想做一些 GPU 计算时加快计算速度,它只是为了加速你的神经网络，那么你当然需要使用你的 GPU,这就是将张量移动到 GPU 的方法

tensor([[ 1.3876,  1.0988,  0.6134,  3.0058],
        [ 0.3976,  0.8143,  1.0441, -0.7786],
        [ 0.3195, -0.1209,  0.4599,  1.2116],
        [ 1.5573,  0.5661, -0.8855,  2.6880]], device='cuda:0')


In [ ]:
#Provide Easy switching between CPU and GPU
CUDA = torch.cuda.is_available()
print(CUDA)
if CUDA:
    add_result = add_result.cuda()
    print(add_result)

True
tensor([[ 1.3876,  1.0988,  0.6134,  3.0058],
        [ 0.3976,  0.8143,  1.0441, -0.7786],
        [ 0.3195, -0.1209,  0.4599,  1.2116],
        [ 1.5573,  0.5661, -0.8855,  2.6880]], device='cuda:0')


In [ ]:
#You can also convert a list to a tensor
a = [2,3,4,1]
print(a)
to_list = torch.tensor(a)
print(to_list, to_list.dtype)

[2, 3, 4, 1]
tensor([2, 3, 4, 1]) torch.int64


In [ ]:
data =  [[1., 2.], [3., 4.],
         [5., 6.], [7., 8.]]
T = torch.tensor(data)
print(T, T.dtype)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]]) torch.float32


## Tensor Concatenation

In [ ]:
#Tensor Concatenation 张量连接
first_1 = torch.randn(2, 5)
print(first_1)
second_1 = torch.randn(3, 5)
print(second_1)
#Concatenate along the 0 dimension (concatenate rows)
con_1 = torch.cat([first_1, second_1])  # 按列连接 上下
print('\n')
print(con_1)
print('\n')
first_2 = torch.randn(2, 3)
print(first_2)
second_2 = torch.randn(2, 5)
print(second_2)
# Concatenate along the 1 dimension (concatenate columns)
con_2 = torch.cat([first_2, second_2], 1) # 按行连接 左右
print('\n')
print(con_2)
print('\n')

tensor([[ 1.3764, -0.8490,  0.2908,  0.7473, -1.0248],
        [ 0.9702, -0.0897, -1.7068, -0.0574, -0.4710]])
tensor([[-0.8916,  1.1353, -0.0939,  0.5517,  1.9676],
        [ 2.3614, -0.4936, -1.3871, -1.6027,  0.7342],
        [-1.5270, -0.1521,  1.3709,  0.8060, -0.1269]])


tensor([[ 1.3764, -0.8490,  0.2908,  0.7473, -1.0248],
        [ 0.9702, -0.0897, -1.7068, -0.0574, -0.4710],
        [-0.8916,  1.1353, -0.0939,  0.5517,  1.9676],
        [ 2.3614, -0.4936, -1.3871, -1.6027,  0.7342],
        [-1.5270, -0.1521,  1.3709,  0.8060, -0.1269]])


tensor([[ 0.0645, -0.7634,  0.7345],
        [-0.7834, -0.4485,  0.1668]])
tensor([[ 1.9943,  0.9285, -0.0825,  0.0257, -0.8608],
        [-0.4569, -0.5723, -0.2055, -0.5542, -1.4182]])


tensor([[ 0.0645, -0.7634,  0.7345,  1.9943,  0.9285, -0.0825,  0.0257, -0.8608],
        [-0.7834, -0.4485,  0.1668, -0.4569, -0.5723, -0.2055, -0.5542, -1.4182]])




## Adding Dimensions to Tensors

In [ ]:
#Adds a dimension of 1 along a specified index
tensor_1 = torch.tensor([1, 2, 3, 4])
print(tensor_1.shape)
tensor_a = torch.unsqueeze(tensor_1, 0)  #这行代码在 tensor_1 的第0维（即最外层）增加一个维度。结果是一个二维张量 tensor_a，其形状为 [1, 4]
print(tensor_a)
print(tensor_a.shape)
tensor_b = torch.unsqueeze(tensor_1,1) #这行代码在 tensor_1 的第1维（即第二个维度）增加一个维度。结果是一个二维张量 tensor_b，其形状为 [4, 1]
print(tensor_b)
print(tensor_b.shape)
print('\n')
tensor_2 = torch.rand(2,3,4)
print(tensor_2)
print('\n')
tensor_c = tensor_2[:,:,2] #这行代码从 tensor_2 中提取出第三个维度（索引为2）的所有元素，结果是一个形状为 [2, 3] 的二维张量 tensor_c
print(tensor_c)
print(tensor_c.shape) #torch.Size([2, 3])
print('\n')
tensor_d = torch.unsqueeze(tensor_c,2) #这行代码在 tensor_c 的第2维（即第三个维度）增加一个维度。结果是一个形状为 [2, 3, 1] 的三维张量 tensor_d
print(tensor_d)
print(tensor_d.shape)

torch.Size([4])
tensor([[1, 2, 3, 4]])
torch.Size([1, 4])
tensor([[1],
        [2],
        [3],
        [4]])
torch.Size([4, 1])


tensor([[[0.6682, 0.8206, 0.5863, 0.5804],
         [0.3732, 0.7078, 0.2448, 0.7527],
         [0.4562, 0.4420, 0.0282, 0.6540]],

        [[0.9072, 0.2776, 0.5350, 0.9259],
         [0.7868, 0.0957, 0.2005, 0.3234],
         [0.9085, 0.7758, 0.9320, 0.5884]]])


tensor([[0.5863, 0.2448, 0.0282],
        [0.5350, 0.2005, 0.9320]])
torch.Size([2, 3])


tensor([[[0.5863],
         [0.2448],
         [0.0282]],

        [[0.5350],
         [0.2005],
         [0.9320]]])
torch.Size([2, 3, 1])


## AutoGrad

In [ ]:
#Remember, If requires_grad=True, the Tensor object keeps track of how it was created.
x = torch.tensor([1., 2., 3], requires_grad=True)
y = torch.tensor([4., 5., 6], requires_grad=True)
#Notice that both x and y have their required_grad set to true, therefore we an compute gradients with respect to them
z = x + y
print(z)
# z knows that is was created as a result of addition of x and y. It knows that it wasn't read in from a file
print(z.grad_fn) #现在 Z 知道它是被创造出来的, Z 知道这是 X 和 Y 相加的结果,这就是 grad 函数。
#And if we go further on this
s = z.sum()
print(s)
print(s.grad_fn)

tensor([5., 7., 9.], grad_fn=<AddBackward0>)
tensor(21., grad_fn=<SumBackward0>)


In [ ]:
#Now if we backpropagate on s, we can find the gradients of s with respect to x
s.backward()
print(x.grad)
#当我们调用 s.backward 时，然后计算所有的梯度。关于变量的所有梯度,这里的 require_grad 等于 True。所以它只会计算图表中同时显示所有梯度,
#正如我们在理论部分看到的那样。如果我们想访问这里的任何变量，如果我们想得到 S 相对于 X 的梯度，那么这就是我们所做的x.grad。

tensor([1., 1., 1.])


In [ ]:
# By default, Tensors have `requires_grad=False`
x = torch.randn(2, 2)
y = torch.randn(2, 2)
print(x.requires_grad, y.requires_grad)
z = x + y
# So you can't backprop through z
# 因为默认情况下，X 和 Y 的 require_grad 等于 false。现在如果我们选择 Z，好吧，如果我们将 X 和 Y 相加并将结果存储在 Z 中
# 然后我们打印 grad 函数，那么你将得到 None,因为没有跟踪计算,因此，Z 不知道是谁创造了它，因为 X 和 Y 没有require_grad 标志等于 True。
# 所以这意味着你不能通过 Z 进行反向传播。
print(z.grad_fn)
#Another way to set the requires_grad = True is
x.requires_grad_()
y.requires_grad_()
# z contains enough information to compute gradients, as we saw above
z = x + y
print(z.grad_fn)
# If any input to an operation has ``requires_grad=True``, so will the output
print(z.requires_grad)
# Now z has the computation history that relates itself to x and y

new_z = z.detach()
print(new_z.grad_fn)
# z.detach() returns a tensor that shares the same storage as ``z``, but with the computation history forgotten.
#It doesn't know anything about how it was computed.In other words, we have broken the Tensor away from its past history

#You can also stop autograd from tracking history on Tensors. This concept is useful when applying Transfer Learning
#detach 的一个功能,可以停止 AutoGrad通过跟踪张量的历史。这个概念在应用迁移学习时很有用。
print(x.requires_grad)
print((x+10).requires_grad)

with torch.no_grad():
    print((x+10).requires_grad)

False False
None
True
None
True
True
False


In [ ]:
#Let's walk in through one last example
x = torch.ones(2, 2, requires_grad=True)
print(x)
y = x + 2
print(y)
print(y.grad_fn)
z = y * y * 3
out = z.mean()
print(z, out)
out.backward() #out.backward() 计算 out 相对于 x 的梯度，并将结果存储在 x.grad 中
print(x.grad)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)
tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [ ]:
m1 = torch.ones(5,5)
m2 = torch.zeros(5,5)
#Perform element-wise multiplaction
mul = torch.mul(m1,m2)
#Another way to perform element-wise multiplaction
mul_another = m1*m2
print(mul)
print(mul_another)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
